'use client';

import { useState, useEffect } from 'react';
import { Upload, FileText, X } from 'lucide-react';
import { NVCard, NVData } from '@/components/ui/nv-card';
import { fetchNVs, createNV } from '@/lib/api';
import { GoogleGenAI, Type } from '@google/genai';

export default function CommercialPage() {
  const [nvs, setNvs] = useState<NVData[]>([]);
  const [isUploading, setIsUploading] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [pendingNV, setPendingNV] = useState<NVData | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function loadData() {
      const data = await fetchNVs();
      setNvs(data);
      setIsLoading(false);
    }
    loadData();
  }, []);

  const [formData, setFormData] = useState({
    dispatch_address: '',
    contact_name: '',
    contact_phone: '',
    observations: ''
  });

  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];
      setIsUploading(true);
      
      try {
        // Read file as base64
        const reader = new FileReader();
        reader.readAsDataURL(file);
        
        reader.onload = async () => {
          try {
            const base64Data = (reader.result as string).split(',')[1];
            
            const ai = new GoogleGenAI({ apiKey: process.env.NEXT_PUBLIC_GEMINI_API_KEY });
            
            const response = await ai.models.generateContent({
              model: "gemini-3-flash-preview",
              contents: {
                parts: [
                  {
                    inlineData: {
                      mimeType: "application/pdf",
                      data: base64Data,
                    },
                  },
                  {
                    text: "Extrae la información de esta Nota de Venta (NV) o documento de venta. Necesito el número de documento (nv_number), el nombre del cliente (client_name), y la lista de productos (items) con su SKU, descripción y cantidad solicitada (requested_qty). Si no encuentras un SKU, genera uno basado en el nombre.",
                  },
                ],
              },
              config: {
                responseMimeType: "application/json",
                responseSchema: {
                  type: Type.OBJECT,
                  properties: {
                    nv_number: { type: Type.STRING, description: "Número de la nota de venta o documento" },
                    client_name: { type: Type.STRING, description: "Nombre del cliente" },
                    items: {
                      type: Type.ARRAY,
                      items: {
                        type: Type.OBJECT,
                        properties: {
                          sku: { type: Type.STRING, description: "Código SKU del producto" },
                          description: { type: Type.STRING, description: "Descripción del producto" },
                          requested_qty: { type: Type.INTEGER, description: "Cantidad solicitada" }
                        },
                        required: ["sku", "description", "requested_qty"]
                      }
                    }
                  },
                  required: ["nv_number", "client_name", "items"]
                }
              }
            });

            if (response.text) {
              const extractedData = JSON.parse(response.text);
              
              const extractedNV: NVData = {
                id: '', // Will be generated by Supabase
                nv_number: extractedData.nv_number || `NV-${Math.floor(Math.random() * 10000)}`,
                client_name: extractedData.client_name || 'Cliente Desconocido',
                status: 'pendiente',
                items: extractedData.items.map((item: any) => ({
                  id: Math.random().toString(36).substring(2, 9), // Temporary unique ID for React keys
                  sku: item.sku || 'SKU-DESC',
                  description: item.description || 'Producto sin descripción',
                  requested_qty: item.requested_qty || 1,
                  picked_qty: 0,
                  packed_qty: 0,
                  status: 'pendiente'
                }))
              };
              
              setPendingNV(extractedNV);
              setShowModal(true);
            } else {
              throw new Error("No se pudo extraer información del PDF.");
            }
          } catch (error) {
            console.error("Error procesando PDF con IA:", error);
            alert("Hubo un error al procesar el PDF con la IA. Por favor, intenta de nuevo.");
          } finally {
            setIsUploading(false);
          }
        };
        
        reader.onerror = () => {
          console.error("Error leyendo el archivo");
          alert("Error al leer el archivo PDF.");
          setIsUploading(false);
        };
      } catch (error) {
        console.error("Error general:", error);
        setIsUploading(false);
      }
    }
  };

  const handleSave = async () => {
    if (pendingNV) {
      // Create NV in Supabase
      const newNV = await createNV(
        {
          nv_number: pendingNV.nv_number,
          client_name: pendingNV.client_name,
          status: pendingNV.status,
          dispatch_address: formData.dispatch_address,
          contact_name: formData.contact_name,
          contact_phone: formData.contact_phone,
          observations: formData.observations
        },
        pendingNV.items.map(item => ({
          sku: item.sku,
          description: item.description,
          requested_qty: item.requested_qty,
          picked_qty: item.picked_qty,
          packed_qty: item.packed_qty,
          status: item.status
        }))
      );

      if (newNV) {
        setNvs([newNV, ...nvs]);
      } else {
        alert('Error al guardar la NV en la base de datos');
      }

      setShowModal(false);
      setPendingNV(null);
      setFormData({ dispatch_address: '', contact_name: '', contact_phone: '', observations: '' });
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-antko-dark">Panel Comercial</h1>
          <p className="text-gray-500">Subir y hacer seguimiento de Notas de Venta (NV)</p>
        </div>
        <div>
          <label className="flex items-center gap-2 bg-antko-primary text-white px-4 py-2 rounded-lg cursor-pointer hover:bg-antko-primary/90 transition-colors">
            <Upload className="w-4 h-4" />
            <span>{isUploading ? 'Procesando IA...' : 'Subir NV (PDF)'}</span>
            <input type="file" accept=".pdf" className="hidden" onChange={handleUpload} disabled={isUploading} />
          </label>
        </div>
      </div>

      {isLoading ? (
        <div className="flex justify-center items-center py-12">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-antko-primary"></div>
        </div>
      ) : nvs.length === 0 ? (
        <div className="text-center py-12 bg-gray-50 rounded-xl border border-dashed border-gray-300">
          <p className="text-gray-500">No hay Notas de Venta registradas. Sube un PDF para comenzar.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4">
          {nvs.map((nv) => (
            <NVCard key={nv.id} nv={nv} />
          ))}
        </div>
      )}

      {/* Confirmation Modal */}
      {showModal && pendingNV && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-2xl flex flex-col max-h-[90vh] overflow-hidden">
            <div className="flex justify-between items-center p-6 border-b border-gray-100 shrink-0">
              <h2 className="text-xl font-bold text-antko-dark">Confirmar Nota de Venta</h2>
              <button onClick={() => setShowModal(false)} className="text-gray-400 hover:text-gray-600">
                <X className="w-6 h-6" />
              </button>
            </div>
            
            <div className="p-6 space-y-6 overflow-y-auto">
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Datos Extraídos por IA</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <span className="block text-xs text-gray-500">Número NV</span>
                    <span className="font-medium">{pendingNV.nv_number}</span>
                  </div>
                  <div>
                    <span className="block text-xs text-gray-500">Cliente</span>
                    <span className="font-medium">{pendingNV.client_name}</span>
                  </div>
                </div>
                <div className="mt-4">
                  <span className="block text-xs text-gray-500 mb-2">Productos</span>
                  <ul className="text-sm space-y-1">
                    {pendingNV.items.map(item => (
                      <li key={item.id} className="flex justify-between">
                        <span>{item.sku} - {item.description}</span>
                        <span className="font-medium">Cant: {item.requested_qty}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="space-y-4">
                <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider">Información Opcional de Despacho</h3>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Dirección de despacho</label>
                  <input 
                    type="text" 
                    value={formData.dispatch_address}
                    onChange={(e) => setFormData({...formData, dispatch_address: e.target.value})}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 outline-none focus:border-antko-primary"
                    placeholder="Ej: Av. Las Industrias 1234, Santiago"
                  />
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Nombre contacto</label>
                    <input 
                      type="text" 
                      value={formData.contact_name}
                      onChange={(e) => setFormData({...formData, contact_name: e.target.value})}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2 outline-none focus:border-antko-primary"
                      placeholder="Ej: Juan Pérez"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Teléfono contacto</label>
                    <input 
                      type="text" 
                      value={formData.contact_phone}
                      onChange={(e) => setFormData({...formData, contact_phone: e.target.value})}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2 outline-none focus:border-antko-primary"
                      placeholder="Ej: +56 9 1234 5678"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Observaciones</label>
                  <textarea 
                    value={formData.observations}
                    onChange={(e) => setFormData({...formData, observations: e.target.value})}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 outline-none focus:border-antko-primary h-20 resize-none"
                    placeholder="Instrucciones especiales de entrega..."
                  ></textarea>
                </div>
              </div>
            </div>

            <div className="p-6 border-t border-gray-100 flex justify-end gap-3 bg-gray-50 shrink-0">
              <button 
                onClick={() => setShowModal(false)}
                className="px-4 py-2 rounded-lg font-medium text-gray-600 hover:bg-gray-200 transition-colors"
              >
                Cancelar
              </button>
              <button 
                onClick={handleSave}
                className="px-6 py-2 rounded-lg font-medium bg-antko-primary text-white hover:bg-antko-primary/90 transition-colors"
              >
                Cargar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
